name: Build_ChatGPT_Extension

on:
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Last Successful Build SHA and Branch
      id: main
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: commit } = await github.repos.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: process.env.GITHUB_REF
          });
          return {
            branch_sha: commit.sha
          };


    - name: Get All Commits Since Last Build
      id: get_commits
      run: |
        git log --pretty=oneline --abbrev-commit --no-decorate ${LAST_BUILD_SHA}..${GITHUB_SHA} > commits.txt
      env:
        LAST_BUILD_SHA: ${{ steps.last_build.outputs.branch_sha }}
        GITHUB_SHA: ${{ steps.main.outputs.branch_sha }}

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Patch Extension
      run: |
        7z a -r -tzip gptchat_extension_chrome.zip build/chromium/
        7z a -r -tzip gptchat_extension_firefox.zip build/firefox/
        7z a -r -tzip gptchat_extension.zip ./gptchat_extension_chrome.zip ./gptchat_extension_firefox.zip
        
    - name: Load Chrome Build
      uses: actions/upload-artifact@v2
      with:
        name: Browser Build for Chrome
        path: gptchat_extension_chrome.zip
        
    - name: Load Firefox Build
      uses: actions/upload-artifact@v2
      with:
        name: Browser Build for Firefox
        path: gptchat_extension_firefox.zip
           
    - name: Uploading Kernel Package to GH-Release
      uses: ncipollo/release-action@v1.8.6
      with:
        artifacts: gptchat_extension.zip
        name: " gptchat_extension "
        tag: " ${{ github.run_number }}_gptchat_extension"
        bodyFile: "commits.txt"
        token: ${{ secrets.GITHUB_TOKEN }}
        


